cl_weight: 0.0
clip_gn: 100.0
config_file: ''
conv: full
data: mnist
data_seed: 0
epochs: 500
hh_factors: 2
hid_dim: []
k: 4
l: 2
log_each: 1
logits: true
lr: 0.001
lr_gamma: 0.5
lr_schedule: linear
lr_steps: []
lr_warmup: 10
model: mnist-masked
name: em vs mle
num_examples: -1
pretrained: ''
root: ''
seed: 0
ssl_conv: full
ssl_dim: 196
ssl_hd: 256
ssl_hh: 2
ssl_k: 4
ssl_l: 2
ssl_model: cond-flow
ssl_nclasses: 10
status: done
sup_ohe: true
sup_sample_weight: 0.5
sup_weight: 1.0
supervised: 100
test_bs: 512
tmp: false
train_bs: 256
weight_decay: 1.0e-05

time: '2019-04-20T13:33:10'
id: 118
